/**
 * RevokeAccessRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: agreements
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * RevokeAccessRepository Port
 *
 * DDD: Application port for revokeaccessrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { RevokeAgreementAccessInput, RevokeAgreementAccessOutput } from "../dto/revoke-access.dto";
export interface RevokeAccessRepository {
  revokeAgreementAccess(input: RevokeAgreementAccessInput): Promise<RevokeAgreementAccessOutput>;
}

export type { RevokeAgreementAccessInput, RevokeAgreementAccessOutput } from "../dto/revoke-access.dto";
