/**
 * ServiceAgreementRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: agreements
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ServiceAgreementRepository Port
 *
 * DDD: Application port for serviceagreementrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { CreateServiceAgreementInput, CreateServiceAgreementOutput, GetServiceAgreementInput, GetServiceAgreementOutput, ListServiceAgreementsInput, ListServiceAgreementsOutput } from "../dto/service-agreement.dto";
export interface ServiceAgreementRepository {
  listServiceAgreements(input: ListServiceAgreementsInput): Promise<ListServiceAgreementsOutput>;
  createServiceAgreement(input: CreateServiceAgreementInput): Promise<CreateServiceAgreementOutput>;
  getServiceAgreement(input: GetServiceAgreementInput): Promise<GetServiceAgreementOutput>;
}

export type { CreateServiceAgreementInput, CreateServiceAgreementOutput, GetServiceAgreementInput, GetServiceAgreementOutput, ListServiceAgreementsInput, ListServiceAgreementsOutput } from "../dto/service-agreement.dto";
