/**
 * Repository interface for RewardEpoch
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: rewards
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CreateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  RewardEpochEntity
} from "../models/reward-epoch.entity.js";
import type {
  ListRewardEpochsParams,
  RewardEpoch
} from "../types/index.js";
/**
 * RewardEpochRepository Interface
 */
export interface RewardEpochRepository extends CreateReadRepository<RewardEpochEntity, RewardEpoch, string, ListRewardEpochsParams> {

}
