/**
 * Handlers for BindOutcome
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: arbitration
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { ArbitrationDomainModule } from "../dependencies/arbitration-ddd.dependencies.js";
import type { BindArbitrationOutcomeInput } from "@veridrop/services/arbitration";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for POST /v0/arbitration-cases/{caseId}/bind-outcome
 * Operation: bindArbitrationOutcome
 */
export async function bindArbitrationOutcome(
  request: FastifyRequest<{ Params: { caseId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: ArbitrationDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: BindArbitrationOutcomeInput = {
    caseId: request.params.caseId,
  };
  const result = await deps.useCases.bindOutcomes.get.execute(input);
  return reply.code(200).send(result);
}


