/**
 * ProofPolicy DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: services
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ProofPolicy DTOs
 *
 * DDD: Application DTOs for ProofPolicy use cases.
 */

import type { SetServiceProofPolicyParams, SetServiceProofPolicyRequestInput } from "@veridrop/core/services/types";

export type SetServiceProofPolicyInput = SetServiceProofPolicyParams & SetServiceProofPolicyRequestInput;

export type SetServiceProofPolicyOutput = {};
