/**
 * Service DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: services
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Service DTOs
 *
 * DDD: Application DTOs for Service use cases.
 */

import type { GetServiceParams, ListServicesParams, RegisterServiceRequestInput } from "@veridrop/core/services/types";

export type ListServicesInput = ListServicesParams;

export type RegisterServiceInput = RegisterServiceRequestInput;

export type GetServiceInput = GetServiceParams;

export type ListServicesOutput = {};

export type RegisterServiceOutput = {};

export type GetServiceOutput = {};
