/**
 * Dependency Container
 *
 * AUTO-GENERATED by codegen (api_server_domain_dependencies). Do not edit by hand.
 * Regenerate with: pnpm run codegen (domain list from platform/api-server/src/domains rescan).
 *
 * Manages dependency creation and caching per domain.
 */

import type { AdapterDynamoDBClient } from "@veridrop/adapters";
import { getDynamoClientInstance } from "../lib/dependencies/domain-dependencies.js";
import { executionContextService } from "../lib/context/execution-context.service.js";
import {
  buildAgreementsDomainModule,
  buildArbitrationDomainModule,
  buildCurationDomainModule,
  buildGovernanceDomainModule,
  buildIdentityDomainModule,
  buildParticipantsDomainModule,
  buildProofsDomainModule,
  buildProvenanceDomainModule,
  buildRewardsDomainModule,
  buildServicesDomainModule,
} from "../domains/index.js";
import type {
  AgreementsDomainModule,
  ArbitrationDomainModule,
  CurationDomainModule,
  GovernanceDomainModule,
  IdentityDomainModule,
  ParticipantsDomainModule,
  ProofsDomainModule,
  ProvenanceDomainModule,
  RewardsDomainModule,
  ServicesDomainModule,
} from "../domains/index.js";

class DependencyContainer {
  private readonly dynamoClient: AdapterDynamoDBClient;

  private agreementsModule: AgreementsDomainModule | null = null;
  private arbitrationModule: ArbitrationDomainModule | null = null;
  private curationModule: CurationDomainModule | null = null;
  private governanceModule: GovernanceDomainModule | null = null;
  private identityModule: IdentityDomainModule | null = null;
  private participantsModule: ParticipantsDomainModule | null = null;
  private proofsModule: ProofsDomainModule | null = null;
  private provenanceModule: ProvenanceDomainModule | null = null;
  private rewardsModule: RewardsDomainModule | null = null;
  private servicesModule: ServicesDomainModule | null = null;

  constructor(dynamoClient: AdapterDynamoDBClient) {
    this.dynamoClient = dynamoClient;
  }

  /**
   * Get agreements domain module
   */
  getAgreementsDependencies(): AgreementsDomainModule {
    if (!this.agreementsModule) {
      this.agreementsModule = buildAgreementsDomainModule(this.dynamoClient);
    }
    return this.agreementsModule;
  }

  /**
   * Get arbitration domain module
   */
  getArbitrationDependencies(): ArbitrationDomainModule {
    if (!this.arbitrationModule) {
      this.arbitrationModule = buildArbitrationDomainModule(this.dynamoClient);
    }
    return this.arbitrationModule;
  }

  /**
   * Get curation domain module
   */
  getCurationDependencies(): CurationDomainModule {
    if (!this.curationModule) {
      this.curationModule = buildCurationDomainModule(this.dynamoClient);
    }
    return this.curationModule;
  }

  /**
   * Get governance domain module
   */
  getGovernanceDependencies(): GovernanceDomainModule {
    if (!this.governanceModule) {
      this.governanceModule = buildGovernanceDomainModule(this.dynamoClient);
    }
    return this.governanceModule;
  }

  /**
   * Get identity domain module
   */
  getIdentityDependencies(): IdentityDomainModule {
    if (!this.identityModule) {
      this.identityModule = buildIdentityDomainModule(this.dynamoClient);
    }
    return this.identityModule;
  }

  /**
   * Get participants domain module
   */
  getParticipantsDependencies(): ParticipantsDomainModule {
    if (!this.participantsModule) {
      this.participantsModule = buildParticipantsDomainModule(this.dynamoClient);
    }
    return this.participantsModule;
  }

  /**
   * Get proofs domain module
   */
  getProofsDependencies(): ProofsDomainModule {
    if (!this.proofsModule) {
      this.proofsModule = buildProofsDomainModule(this.dynamoClient);
    }
    return this.proofsModule;
  }

  /**
   * Get provenance domain module
   */
  getProvenanceDependencies(): ProvenanceDomainModule {
    if (!this.provenanceModule) {
      this.provenanceModule = buildProvenanceDomainModule(this.dynamoClient);
    }
    return this.provenanceModule;
  }

  /**
   * Get rewards domain module
   */
  getRewardsDependencies(): RewardsDomainModule {
    if (!this.rewardsModule) {
      this.rewardsModule = buildRewardsDomainModule(this.dynamoClient);
    }
    return this.rewardsModule;
  }

  /**
   * Get services domain module
   */
  getServicesDependencies(): ServicesDomainModule {
    if (!this.servicesModule) {
      this.servicesModule = buildServicesDomainModule(this.dynamoClient);
    }
    return this.servicesModule;
  }

  clearAgreementsDependencies(): void { this.agreementsModule = null; }
  clearArbitrationDependencies(): void { this.arbitrationModule = null; }
  clearCurationDependencies(): void { this.curationModule = null; }
  clearGovernanceDependencies(): void { this.governanceModule = null; }
  clearIdentityDependencies(): void { this.identityModule = null; }
  clearParticipantsDependencies(): void { this.participantsModule = null; }
  clearProofsDependencies(): void { this.proofsModule = null; }
  clearProvenanceDependencies(): void { this.provenanceModule = null; }
  clearRewardsDependencies(): void { this.rewardsModule = null; }
  clearServicesDependencies(): void { this.servicesModule = null; }

  getAgreementsDependenciesForRequest(): AgreementsDomainModule {
    return this.getAgreementsDependencies();
  }

  getArbitrationDependenciesForRequest(): ArbitrationDomainModule {
    return this.getArbitrationDependencies();
  }

  getCurationDependenciesForRequest(): CurationDomainModule {
    return this.getCurationDependencies();
  }

  getGovernanceDependenciesForRequest(): GovernanceDomainModule {
    return this.getGovernanceDependencies();
  }

  getIdentityDependenciesForRequest(): IdentityDomainModule {
    return this.getIdentityDependencies();
  }

  getParticipantsDependenciesForRequest(): ParticipantsDomainModule {
    return this.getParticipantsDependencies();
  }

  getProofsDependenciesForRequest(): ProofsDomainModule {
    return this.getProofsDependencies();
  }

  getProvenanceDependenciesForRequest(): ProvenanceDomainModule {
    return this.getProvenanceDependencies();
  }

  getRewardsDependenciesForRequest(): RewardsDomainModule {
    return this.getRewardsDependencies();
  }

  getServicesDependenciesForRequest(): ServicesDomainModule {
    return this.getServicesDependencies();
  }

  /**
   * Clear all caches
   */
  clearAllCaches(): void {
    this.agreementsModule = null;
    this.arbitrationModule = null;
    this.curationModule = null;
    this.governanceModule = null;
    this.identityModule = null;
    this.participantsModule = null;
    this.proofsModule = null;
    this.provenanceModule = null;
    this.rewardsModule = null;
    this.servicesModule = null;
  }
}

let dependencyContainerInstance: DependencyContainer | null = null;

export function getDependencyContainer(): DependencyContainer {
  if (!dependencyContainerInstance) {
    const dynamoClient = getDynamoClientInstance();
    dependencyContainerInstance = new DependencyContainer(dynamoClient);
  }
  return dependencyContainerInstance;
}
