/**
 * ChallengeEscape DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: provenance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ChallengeEscape DTOs
 *
 * DDD: Application DTOs for ChallengeEscape use cases.
 */

import type { ChallengeDataEscapeParams, ChallengeDataEscapeRequestInput } from "@veridrop/core/provenance/types";

export type ChallengeDataEscapeInput = ChallengeDataEscapeParams & ChallengeDataEscapeRequestInput;

export type ChallengeDataEscapeOutput = {};
