/**
 * GetDropPosition handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: curation
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { getDropPosition } from "@veridrop/api-server/domains/curation/handlers";
import type { CurationDDDDependencies } from "@veridrop/api-server/domains/curation";
import { createDropPosition as createDropPositionEntity } from "@veridrop/factories/curation";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@veridrop/tests/shared";
import { CURATION_USE_CASES } from "../__factories__/use-cases.js";

describe("GetDropPosition", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: CurationDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<CurationDDDDependencies>(
      CURATION_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with entity when found", async () => {
    const entity = createDropPositionEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    vi.spyOn(mockDeps.executeGetDropPosition, "execute").mockResolvedValue(useCaseResult);
    mockRequest.params = { positionId: entity.id };

    await getDropPosition(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeGetDropPosition.execute).toHaveBeenCalledWith(expect.objectContaining({ positionId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

  it("should return error when entity not found", async () => {
    const nonExistentId = "non-existent-id";
    mockRequest.params = { positionId: nonExistentId };
    
    vi.spyOn(mockDeps.executeGetDropPosition, "execute").mockRejectedValue(
      new Error("Entity not found")
    );

    await expect(
      getDropPosition(mockRequest, mockReply, mockDeps)
    ).rejects.toThrow();
  });

});
