/**
 * Routes for ChallengeEscape
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: provenance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { challengeDataEscape } from "../handlers/challenge-escape.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function challengeEscapeRoutes(fastify: FastifyInstance) {
  // POST /v0/provenance-records/{provenanceId}/challenge-escape (unscoped; scope set for security middleware)
  fastify.post(
    "/v0/provenance-records/:provenanceId/challenge-escape",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { provenanceId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getProvenanceDependenciesForRequest();
        await challengeDataEscape(request, reply, deps);
      });
    }
  );


}
