/**
 * Routes for ProvenanceRecord
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: provenance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { getProvenanceRecord, listProvenanceRecords, recordProvenance } from "../handlers/provenance-record.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function provenanceRecordRoutes(fastify: FastifyInstance) {
  // GET /v0/provenance-records (unscoped; scope set for security middleware)
  fastify.get(
    "/v0/provenance-records",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getProvenanceDependenciesForRequest();
        await listProvenanceRecords(request, reply, deps);
      });
    }
  );


  // POST /v0/provenance-records (unscoped; scope set for security middleware)
  fastify.post(
    "/v0/provenance-records",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getProvenanceDependenciesForRequest();
        await recordProvenance(request, reply, deps);
      });
    }
  );


  // GET /v0/provenance-records/{provenanceId} (unscoped; scope set for security middleware)
  fastify.get(
    "/v0/provenance-records/:provenanceId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { provenanceId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getProvenanceDependenciesForRequest();
        await getProvenanceRecord(request, reply, deps);
      });
    }
  );


}
