/**
 * GetArbitrationCase DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: arbitration
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { GetArbitrationCaseParams } from "@veridrop/core/arbitration";

export function createGetArbitrationCaseRequest(overrides: Partial<GetArbitrationCaseParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
