/**
 * GetService DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: services
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { GetServiceParams } from "@veridrop/core/services";

export function createGetServiceRequest(overrides: Partial<GetServiceParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
