/**
 * DropPosition Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: curation
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/curation.openapi.types.js";
import { schemas } from "../schemas/curation.schemas.js";

/**
 * Entity: DropPositionEntity
 * Description: Represents the DropPosition domain model.
 * Source: schemas.DropPosition
 * Type: Domain Entity (API)
 */
export const DropPositionEntitySchema = schemas.DropPosition;
export type DropPositionEntity = components["schemas"]["DropPosition"];
