/**
 * StakeEvent Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: curation
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/curation.openapi.types.js";
import { schemas } from "../schemas/curation.schemas.js";

/**
 * Entity: StakeEventEntity
 * Description: Represents the StakeEvent domain model.
 * Source: schemas.StakeEvent
 * Type: Domain Entity (API)
 */
export const StakeEventEntitySchema = schemas.StakeEvent;
export type StakeEventEntity = components["schemas"]["StakeEvent"];
