/**
 * OpenArbitrationCase handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: arbitration
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { openArbitrationCase } from "@veridrop/api-server/domains/arbitration/handlers";
import type { ArbitrationDDDDependencies } from "@veridrop/api-server/domains/arbitration";
import { createArbitrationCase as createArbitrationCaseEntity } from "@veridrop/factories/arbitration";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@veridrop/tests/shared";
import { ARBITRATION_USE_CASES } from "../__factories__/use-cases.js";

describe("OpenArbitrationCase", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: ArbitrationDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<ArbitrationDDDDependencies>(
      ARBITRATION_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 201 with created entity", async () => {
    const input = {} as any;
    const entity = createArbitrationCaseEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeOpenArbitrationCase, "execute").mockResolvedValue(useCaseResult);

    await openArbitrationCase(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeOpenArbitrationCase.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(201);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
