/**
 * Handlers for AcceptDelivery
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: agreements
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { AgreementsDomainModule } from "../dependencies/agreements-ddd.dependencies.js";
import type { AcceptAgreementDeliveryInput } from "@veridrop/services/agreements";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for POST /v0/service-agreements/{agreementId}/accept-delivery
 * Operation: acceptAgreementDelivery
 */
export async function acceptAgreementDelivery(
  request: FastifyRequest<{ Params: { agreementId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: AgreementsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: AcceptAgreementDeliveryInput = {
    agreementId: request.params.agreementId,
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.acceptDeliveries.get.execute(input);
  return reply.code(200).send(result);
}


