/**
 * Handlers for ExportAudit
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: rewards
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { RewardsDomainModule } from "../dependencies/rewards-ddd.dependencies.js";
import type { ExportRewardEpochAuditInput } from "@veridrop/services/rewards";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for POST /v0/reward-epochs/{epochId}/export-audit
 * Operation: exportRewardEpochAudit
 */
export async function exportRewardEpochAudit(
  request: FastifyRequest<{ Params: { epochId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: RewardsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ExportRewardEpochAuditInput = {
    epochId: request.params.epochId,
  };
  const result = await deps.useCases.exportAudits.list.execute(input);
  return reply.code(200).send(result);
}


