/**
 * Repository interface for ParameterVersion
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: governance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CreateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  ParameterVersionEntity
} from "../models/parameter-version.entity.js";
import type {
  ListParameterVersionsParams,
  ParameterVersion
} from "../types/index.js";
/**
 * ParameterVersionRepository Interface
 */
export interface ParameterVersionRepository extends CreateReadRepository<ParameterVersionEntity, ParameterVersion, string, ListParameterVersionsParams> {

}
