/**
 * ExecuteListServiceAgreements - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: agreements
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListServiceAgreements Use Case
 *
 * DDD: Application use case for list ServiceAgreement.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListServiceAgreementsInput, ListServiceAgreementsOutput } from "../dto/service-agreement.dto";
import type { ExecutionContextService, IdGeneratorService } from "@veridrop/services/_shared/index.js";
import type { ServiceAgreementRepository } from "../ports";

export class ExecuteListServiceAgreements {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly serviceAgreement: ServiceAgreementRepository
  ) {}

  async execute(input: ListServiceAgreementsInput): Promise<ListServiceAgreementsOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.agrId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.serviceAgreement.listServiceAgreements({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListServiceAgreementsOutput;
  }
}
