/**
 * ExecuteGetServiceAgreement - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: agreements
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteGetServiceAgreement Use Case
 *
 * DDD: Application use case for get ServiceAgreement.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { GetServiceAgreementInput, GetServiceAgreementOutput } from "../dto/service-agreement.dto";
import type { ExecutionContextService, IdGeneratorService } from "@veridrop/services/_shared/index.js";
import type { ServiceAgreementRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteGetServiceAgreement {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly serviceAgreement: ServiceAgreementRepository
  ) {}

  async execute(input: GetServiceAgreementInput): Promise<GetServiceAgreementOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.agrId();

    // All field names extracted from OpenAPI spec: none
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).agreementId) {
      throw new ValidationError("agreementId is required");
    }
    const agreementId = (input as any).agreementId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.serviceAgreement.getServiceAgreement({ agreementId: agreementId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${agreementId}`);
    }

    return entity as GetServiceAgreementOutput;
  }
}
