/**
 * ServiceAgreement Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: agreements
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/agreements.openapi.types.js";
import { schemas } from "../schemas/agreements.schemas.js";

/**
 * Entity: ServiceAgreementEntity
 * Description: Represents the ServiceAgreement domain model.
 * Source: schemas.ServiceAgreement
 * Type: Domain Entity (API)
 */
export const ServiceAgreementEntitySchema = schemas.ServiceAgreement;
export type ServiceAgreementEntity = components["schemas"]["ServiceAgreement"];
