/**
 * ExecuteOpenRewardEpoch - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: rewards
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteOpenRewardEpoch Use Case
 *
 * DDD: Application use case for get RewardEpoch.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { OpenRewardEpochInput, OpenRewardEpochOutput } from "../dto/reward-epoch.dto";
import type { ExecutionContextService, IdGeneratorService } from "@veridrop/services/_shared/index.js";
import type { RewardEpochRepository } from "../ports";
import { NotFoundError } from "../errors";

export class ExecuteOpenRewardEpoch {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly rewardEpoch: RewardEpochRepository
  ) {}

  async execute(input: OpenRewardEpochInput): Promise<OpenRewardEpochOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.rwdId();

    // All field names extracted from OpenAPI spec: periodEnd, periodStart
    // Load entity via repository (no ID field - uses input directly, pass correlation ID for response meta)
    const entity = await this.rewardEpoch.openRewardEpoch({ ...input, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found`);
    }

    return entity as OpenRewardEpochOutput;
  }
}
