/**
 * ExecuteGetProvenanceRecord - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: provenance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteGetProvenanceRecord Use Case
 *
 * DDD: Application use case for get ProvenanceRecord.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { GetProvenanceRecordInput, GetProvenanceRecordOutput } from "../dto/provenance-record.dto";
import type { ExecutionContextService, IdGeneratorService } from "@veridrop/services/_shared/index.js";
import type { ProvenanceRecordRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteGetProvenanceRecord {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly provenanceRecord: ProvenanceRecordRepository
  ) {}

  async execute(input: GetProvenanceRecordInput): Promise<GetProvenanceRecordOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.prvId();

    // All field names extracted from OpenAPI spec: none
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).provenanceId) {
      throw new ValidationError("provenanceId is required");
    }
    const provenanceId = (input as any).provenanceId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.provenanceRecord.getProvenanceRecord({ provenanceId: provenanceId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${provenanceId}`);
    }

    return entity as GetProvenanceRecordOutput;
  }
}
