/**
 * Handlers for DropPosition
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: curation
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { CurationDomainModule } from "../dependencies/curation-ddd.dependencies.js";
import type { GetDropPositionInput, ListDropPositionsInput, OpenDropPositionInput } from "@veridrop/services/curation";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v0/drop-positions
 * Operation: listDropPositions
 */
export async function listDropPositions(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[], serviceId?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: CurationDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListDropPositionsInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.dropPositions.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v0/drop-positions
 * Operation: openDropPosition
 */
export async function openDropPosition(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: CurationDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: OpenDropPositionInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.dropPositions.get.execute(input);
  return reply.code(201).send(result);
}


/**
 * Handler for GET /v0/drop-positions/{positionId}
 * Operation: getDropPosition
 */
export async function getDropPosition(
  request: FastifyRequest<{ Params: { positionId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: CurationDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetDropPositionInput = {
    positionId: request.params.positionId,
  };
  const result = await deps.useCases.dropPositions.get.execute(input);
  return reply.code(200).send(result);
}


