/**
 * Handlers for StakeEvent
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: curation
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { CurationDomainModule } from "../dependencies/curation-ddd.dependencies.js";
import type { ListStakeEventsInput } from "@veridrop/services/curation";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v0/drop-positions/{positionId}/stake-events
 * Operation: listStakeEvents
 */
export async function listStakeEvents(
  request: FastifyRequest<{ Params: { positionId: string }; Querystring: { cursor?: string | string[], limit?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: CurationDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListStakeEventsInput = {
    positionId: request.params.positionId,
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.stakeEvents.list.execute(input);
  return reply.code(200).send(result);
}


