/**
 * Handlers for Participant
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: participants
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { ParticipantsDomainModule } from "../dependencies/participants-ddd.dependencies.js";
import type { ApplyParticipantInput, GetParticipantInput, ListParticipantsInput } from "@veridrop/services/participants";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v0/participants
 * Operation: listParticipants
 */
export async function listParticipants(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[], tcrStatus?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: ParticipantsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListParticipantsInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.participants.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v0/participants
 * Operation: applyParticipant
 */
export async function applyParticipant(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: ParticipantsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ApplyParticipantInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.participants.get.execute(input);
  return reply.code(201).send(result);
}


/**
 * Handler for GET /v0/participants/{participantId}
 * Operation: getParticipant
 */
export async function getParticipant(
  request: FastifyRequest<{ Params: { participantId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: ParticipantsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetParticipantInput = {
    participantId: request.params.participantId,
  };
  const result = await deps.useCases.participants.get.execute(input);
  return reply.code(200).send(result);
}


