/**
 * ServiceRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: services
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ServiceRepository Port
 *
 * DDD: Application port for servicerepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { GetServiceInput, GetServiceOutput, ListServicesInput, ListServicesOutput, RegisterServiceInput, RegisterServiceOutput } from "../dto/service.dto";
export interface ServiceRepository {
  listServices(input: ListServicesInput): Promise<ListServicesOutput>;
  registerService(input: RegisterServiceInput): Promise<RegisterServiceOutput>;
  getService(input: GetServiceInput): Promise<GetServiceOutput>;
}

export type { GetServiceInput, GetServiceOutput, ListServicesInput, ListServicesOutput, RegisterServiceInput, RegisterServiceOutput } from "../dto/service.dto";
