/**
 * Repository interface for DropPosition
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: curation
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CreateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  DropPositionEntity
} from "../models/drop-position.entity.js";
import type {
  ListDropPositionsParams,
  DropPosition
} from "../types/index.js";
/**
 * DropPositionRepository Interface
 */
export interface DropPositionRepository extends CreateReadRepository<DropPositionEntity, DropPosition, string, ListDropPositionsParams> {

}
