/**
 * DeliveryProof DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: proofs
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * DeliveryProof DTOs
 *
 * DDD: Application DTOs for DeliveryProof use cases.
 */

import type { GetDeliveryProofParams, ListDeliveryProofsParams, SubmitDeliveryProofRequestInput } from "@veridrop/core/proofs/types";

export type ListDeliveryProofsInput = ListDeliveryProofsParams;

export type SubmitDeliveryProofInput = SubmitDeliveryProofRequestInput;

export type GetDeliveryProofInput = GetDeliveryProofParams;

export type ListDeliveryProofsOutput = {};

export type SubmitDeliveryProofOutput = {};

export type GetDeliveryProofOutput = {};
