/**
 * Slash DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: proofs
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Slash DTOs
 *
 * DDD: Application DTOs for Slash use cases.
 */

import type { SlashDeliveryProofParams, SlashDeliveryProofRequestInput } from "@veridrop/core/proofs/types";

export type SlashDeliveryProofInput = SlashDeliveryProofParams & SlashDeliveryProofRequestInput;

export type SlashDeliveryProofOutput = {};
