/**
 * ProvenanceRecord Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: provenance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/provenance.openapi.types.js";
import { schemas } from "../schemas/provenance.schemas.js";

/**
 * Entity: ProvenanceRecordEntity
 * Description: Represents the ProvenanceRecord domain model.
 * Source: schemas.ProvenanceRecord
 * Type: Domain Entity (API)
 */
export const ProvenanceRecordEntitySchema = schemas.ProvenanceRecord;
export type ProvenanceRecordEntity = components["schemas"]["ProvenanceRecord"];
