/**
 * System Routes - Health check and routes listing
 *
 * AUTO-GENERATED by codegen (api_server_system_routes). Do not edit by hand.
 * Domains and routeExamples are derived from discovered api-server domains and
 * each domain's OpenAPI bundled spec.
 */

import type { FastifyInstance } from "fastify";
import {
  getCoreTableName,
  getBaseTableName,
  getAnalyticsTableName,
} from "@veridrop/adapters";
import { getRegisteredRoutes } from "./route-registry.js";

/**
 * Register system routes (health check, routes listing)
 */
export function registerSystemRoutes(fastify: FastifyInstance): void {
  // Health check (public - no auth required)
  fastify.get("/health", { config: { scope: "public" } }, async () => {
    try {
      const coreTable = getCoreTableName();
      const baseTable = getBaseTableName();
      const analyticsTable = getAnalyticsTableName();
      return {
        status: "ok",
        database: "dynamodb",
        tables: {
          core: coreTable,
          base: baseTable,
          analytics: analyticsTable,
        },
      };
    } catch (error: unknown) {
      const errorMessage =
        error instanceof Error ? error.message : String(error);
      fastify.log.warn({ error: errorMessage }, "Health check failed");
      return { status: "error", database: "disconnected", error: errorMessage };
    }
  });

  // Routes listing endpoint (public)
  fastify.get("/routes", { config: { scope: "public" } }, async () => {
    const domains = [
      "agreements", "arbitration", "curation", "governance", "identity", "participants", "proofs", "provenance", "rewards", "services"
    ];

    const routeExamples: Record<
      string,
      Array<{ method: string; path: string; description?: string }>
    > = {
      agreements: [{ method: "GET", path: "/v0/service-agreements" }, { method: "POST", path: "/v0/service-agreements" }, { method: "GET", path: "/v0/service-agreements/:agreementId" }, { method: "POST", path: "/v0/service-agreements/:agreementId/revoke-access" }, { method: "POST", path: "/v0/service-agreements/:agreementId/accept-delivery" }],
      arbitration: [{ method: "GET", path: "/v0/arbitration-cases" }, { method: "POST", path: "/v0/arbitration-cases" }, { method: "GET", path: "/v0/arbitration-cases/:caseId" }, { method: "POST", path: "/v0/arbitration-cases/:caseId/decide" }, { method: "POST", path: "/v0/arbitration-cases/:caseId/bind-outcome" }],
      curation: [{ method: "GET", path: "/v0/drop-positions" }, { method: "POST", path: "/v0/drop-positions" }, { method: "GET", path: "/v0/drop-positions/:positionId" }, { method: "POST", path: "/v0/drop-positions/:positionId/unstake" }, { method: "GET", path: "/v0/drop-positions/:positionId/stake-events" }],
      governance: [{ method: "GET", path: "/v0/parameter-versions" }, { method: "POST", path: "/v0/parameter-versions" }, { method: "GET", path: "/v0/parameter-versions/:parameterVersionId" }, { method: "POST", path: "/v0/parameter-versions/:parameterVersionId/execute" }, { method: "GET", path: "/v0/governance/emission-pause" }, { method: "POST", path: "/v0/governance/emission-pause" }],
      identity: [{ method: "GET", path: "/v0/tenants/me/api-keys" }, { method: "POST", path: "/v0/tenants/me/api-keys" }, { method: "GET", path: "/v0/tenants/me/api-keys/:keyId" }, { method: "DELETE", path: "/v0/tenants/me/api-keys/:keyId" }, { method: "GET", path: "/v0/tenants/me/users" }, { method: "POST", path: "/v0/tenants/me/users" }, { method: "GET", path: "/v0/tenants/me/users/:userId" }, { method: "PATCH", path: "/v0/tenants/me/users/:userId" }, { method: "POST", path: "/v0/tenants/me/users/:userId/disable" }, { method: "POST", path: "/v0/tenants/me/users/:userId/enable" }, { method: "POST", path: "/v0/auth/login" }, { method: "GET", path: "/v0/auth/me" }, { method: "PATCH", path: "/v0/auth/me" }, { method: "POST", path: "/v0/auth/refresh" }, { method: "POST", path: "/v0/auth/logout" }],
      participants: [{ method: "GET", path: "/v0/participants" }, { method: "POST", path: "/v0/participants" }, { method: "GET", path: "/v0/participants/:participantId" }, { method: "POST", path: "/v0/participants/:participantId/challenge" }, { method: "POST", path: "/v0/participants/:participantId/approve-role" }],
      proofs: [{ method: "GET", path: "/v0/delivery-proofs" }, { method: "POST", path: "/v0/delivery-proofs" }, { method: "GET", path: "/v0/delivery-proofs/:proofId" }, { method: "POST", path: "/v0/delivery-proofs/:proofId/accept" }, { method: "POST", path: "/v0/delivery-proofs/:proofId/reject" }, { method: "POST", path: "/v0/delivery-proofs/:proofId/slash" }],
      provenance: [{ method: "GET", path: "/v0/provenance-records" }, { method: "POST", path: "/v0/provenance-records" }, { method: "GET", path: "/v0/provenance-records/:provenanceId" }, { method: "POST", path: "/v0/provenance-records/:provenanceId/challenge-escape" }],
      rewards: [{ method: "GET", path: "/v0/reward-epochs" }, { method: "POST", path: "/v0/reward-epochs" }, { method: "GET", path: "/v0/reward-epochs/:epochId" }, { method: "POST", path: "/v0/reward-epochs/:epochId/pause" }, { method: "POST", path: "/v0/reward-epochs/:epochId/close" }, { method: "POST", path: "/v0/reward-epochs/:epochId/allocate" }, { method: "POST", path: "/v0/reward-epochs/:epochId/export-audit" }, { method: "POST", path: "/v0/reward-epochs/:epochId/clawback" }],
      services: [{ method: "GET", path: "/v0/services" }, { method: "POST", path: "/v0/services" }, { method: "GET", path: "/v0/services/:serviceId" }, { method: "POST", path: "/v0/services/:serviceId/proof-policy" }, { method: "POST", path: "/v0/services/:serviceId/suspend" }],
    };

    return {
      baseUrl: "http://localhost:4000",
      routePattern: "/orgs/:orgId/{domain}/{resource}",
      authentication:
        "All routes (except /health and /routes) require JWT token in Authorization header",
      domains: domains.sort(),
      routeExamples,
      systemRoutes: [
        { method: "GET", path: "/health", description: "Health check endpoint" },
        { method: "GET", path: "/routes", description: "List available routes" },
      ],
      note: "Replace :orgId with actual organization ID. All domain routes require authentication.",
    };
  });

  // Full route list for API tester page (public)
  fastify.get("/routes/full", { config: { scope: "public" } }, async () => {
    const routes = getRegisteredRoutes();
    const byDomain: Record<
      string,
      Array<{ method: string; path: string }>
    > = {};
    const system: Array<{ method: string; path: string }> = [];
    for (const r of routes) {
      const m = r.path.match(/^\/orgs\/:orgId\/([^/]+)/);
      if (m) {
        const domain = m[1];
        if (!byDomain[domain]) byDomain[domain] = [];
        byDomain[domain].push(r);
      } else {
        system.push(r);
      }
    }
    return {
      baseUrl: "http://localhost:4000",
      total: routes.length,
      system,
      byDomain: Object.keys(byDomain)
        .sort()
        .reduce(
          (acc, k) => ({ ...acc, [k]: byDomain[k] }),
          {} as Record<string, Array<{ method: string; path: string }>>,
        ),
    };
  });
}
