/**
 * DeliveryProofRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: proofs
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * DeliveryProofRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements DeliveryProofRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  DeliveryProofRepository,
} from "@veridrop/services/proofs";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { DeliveryProofRepositoryDdb } from "./delivery-proof-repository.ddb.js";

/**
 * DeliveryProofRepositoryAdapter
 *
 * Implements DeliveryProofRepository port for infrastructure layer.
 */
export class DeliveryProofRepositoryAdapter implements DeliveryProofRepository {
  private readonly ddb: DeliveryProofRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new DeliveryProofRepositoryDdb(this.dynamoClient);
  }

  async listDeliveryProofs(input: Parameters<DeliveryProofRepository['listDeliveryProofs']>[0]): Promise<Awaited<ReturnType<DeliveryProofRepository['listDeliveryProofs']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listDeliveryProofs(input);
  }

  async submitDeliveryProof(input: Parameters<DeliveryProofRepository['submitDeliveryProof']>[0]): Promise<Awaited<ReturnType<DeliveryProofRepository['submitDeliveryProof']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.submitDeliveryProof(input);
  }

  async getDeliveryProof(input: Parameters<DeliveryProofRepository['getDeliveryProof']>[0]): Promise<Awaited<ReturnType<DeliveryProofRepository['getDeliveryProof']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getDeliveryProof(input);
  }
}
