/**
 * DynamoDB repository adapters barrel export
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: proofs
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export * from "./accept-repository.ddb.js";
export * from "./delivery-proof-repository.ddb.js";
export * from "./reject-repository.ddb.js";
export * from "./slash-repository.ddb.js";
export * from "./accept-repository.adapter.js";
export * from "./delivery-proof-repository.adapter.js";
export * from "./reject-repository.adapter.js";
export * from "./slash-repository.adapter.js";
