/**
 * Handlers for ChallengeEscape
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: provenance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { ProvenanceDomainModule } from "../dependencies/provenance-ddd.dependencies.js";
import type { ChallengeDataEscapeInput } from "@veridrop/services/provenance";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for POST /v0/provenance-records/{provenanceId}/challenge-escape
 * Operation: challengeDataEscape
 */
export async function challengeDataEscape(
  request: FastifyRequest<{ Params: { provenanceId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: ProvenanceDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ChallengeDataEscapeInput = {
    provenanceId: request.params.provenanceId,
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.challengeEscapes.get.execute(input);
  return reply.code(200).send(result);
}


