/**
 * ProofPolicyRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: services
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ProofPolicyRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements ProofPolicyRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  ProofPolicyRepository,
} from "@veridrop/services/services";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { ProofPolicyRepositoryDdb } from "./proof-policy-repository.ddb.js";

/**
 * ProofPolicyRepositoryAdapter
 *
 * Implements ProofPolicyRepository port for infrastructure layer.
 */
export class ProofPolicyRepositoryAdapter implements ProofPolicyRepository {
  private readonly ddb: ProofPolicyRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new ProofPolicyRepositoryDdb(this.dynamoClient);
  }

  async setServiceProofPolicy(input: Parameters<ProofPolicyRepository['setServiceProofPolicy']>[0]): Promise<Awaited<ReturnType<ProofPolicyRepository['setServiceProofPolicy']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.setServiceProofPolicy(input);
  }
}
