/**
 * ApproveRoleRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: participants
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ApproveRoleRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements ApproveRoleRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  ApproveRoleRepository,
} from "@veridrop/services/participants";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { ApproveRoleRepositoryDdb } from "./approve-role-repository.ddb.js";

/**
 * ApproveRoleRepositoryAdapter
 *
 * Implements ApproveRoleRepository port for infrastructure layer.
 */
export class ApproveRoleRepositoryAdapter implements ApproveRoleRepository {
  private readonly ddb: ApproveRoleRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new ApproveRoleRepositoryDdb(this.dynamoClient);
  }

  async approveParticipantRole(input: Parameters<ApproveRoleRepository['approveParticipantRole']>[0]): Promise<Awaited<ReturnType<ApproveRoleRepository['approveParticipantRole']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.approveParticipantRole(input);
  }
}
