/**
 * DynamoDB repository adapters barrel export
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: participants
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export * from "./approve-role-repository.ddb.js";
export * from "./challenge-repository.ddb.js";
export * from "./participant-repository.ddb.js";
export * from "./approve-role-repository.adapter.js";
export * from "./challenge-repository.adapter.js";
export * from "./participant-repository.adapter.js";
