/**
 * Routes for Pause
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: rewards
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { pauseRewardEpoch } from "../handlers/pause.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function pauseRoutes(fastify: FastifyInstance) {
  // POST /v0/reward-epochs/{epochId}/pause (unscoped; scope set for security middleware)
  fastify.post(
    "/v0/reward-epochs/:epochId/pause",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { epochId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getRewardsDependenciesForRequest();
        await pauseRewardEpoch(request, reply, deps);
      });
    }
  );


}
