/**
 * ExecuteListArbitrationCases - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: arbitration
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListArbitrationCases Use Case
 *
 * DDD: Application use case for list ArbitrationCase.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListArbitrationCasesInput, ListArbitrationCasesOutput } from "../dto/arbitration-case.dto";
import type { ExecutionContextService, IdGeneratorService } from "@veridrop/services/_shared/index.js";
import type { ArbitrationCaseRepository } from "../ports";

export class ExecuteListArbitrationCases {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly arbitrationCase: ArbitrationCaseRepository
  ) {}

  async execute(input: ListArbitrationCasesInput): Promise<ListArbitrationCasesOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.arbId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.arbitrationCase.listArbitrationCases({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListArbitrationCasesOutput;
  }
}
