/**
 * ExecuteOpenArbitrationCase - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: arbitration
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteOpenArbitrationCase Use Case
 *
 * DDD: Application use case for get ArbitrationCase.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { OpenArbitrationCaseInput, OpenArbitrationCaseOutput } from "../dto/arbitration-case.dto";
import type { ExecutionContextService, IdGeneratorService } from "@veridrop/services/_shared/index.js";
import type { ArbitrationCaseRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteOpenArbitrationCase {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly arbitrationCase: ArbitrationCaseRepository
  ) {}

  async execute(input: OpenArbitrationCaseInput): Promise<OpenArbitrationCaseOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.arbId();

    // All field names extracted from OpenAPI spec: claim, subjectId, subjectType
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).subjectId) {
      throw new ValidationError("subjectId is required");
    }
    const subjectId = (input as any).subjectId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.arbitrationCase.openArbitrationCase({ subjectId: subjectId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${subjectId}`);
    }

    return entity as OpenArbitrationCaseOutput;
  }
}
