/**
 * Routes for DeliveryProof
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: proofs
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { getDeliveryProof, listDeliveryProofs, submitDeliveryProof } from "../handlers/delivery-proof.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function deliveryProofRoutes(fastify: FastifyInstance) {
  // GET /v0/delivery-proofs (unscoped; scope set for security middleware)
  fastify.get(
    "/v0/delivery-proofs",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getProofsDependenciesForRequest();
        await listDeliveryProofs(request, reply, deps);
      });
    }
  );


  // POST /v0/delivery-proofs (unscoped; scope set for security middleware)
  fastify.post(
    "/v0/delivery-proofs",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getProofsDependenciesForRequest();
        await submitDeliveryProof(request, reply, deps);
      });
    }
  );


  // GET /v0/delivery-proofs/{proofId} (unscoped; scope set for security middleware)
  fastify.get(
    "/v0/delivery-proofs/:proofId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { proofId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getProofsDependenciesForRequest();
        await getDeliveryProof(request, reply, deps);
      });
    }
  );


}
