/**
 * Routes index
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: proofs
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export { acceptRoutes } from "./accept.routes.js";
export { deliveryProofRoutes } from "./delivery-proof.routes.js";
export { rejectRoutes } from "./reject.routes.js";
export { slashRoutes } from "./slash.routes.js";
