/**
 * Routes for AcceptDelivery
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: agreements
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { acceptAgreementDelivery } from "../handlers/accept-delivery.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function acceptDeliveryRoutes(fastify: FastifyInstance) {
  // POST /v0/service-agreements/{agreementId}/accept-delivery (unscoped; scope set for security middleware)
  fastify.post(
    "/v0/service-agreements/:agreementId/accept-delivery",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { agreementId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getAgreementsDependenciesForRequest();
        await acceptAgreementDelivery(request, reply, deps);
      });
    }
  );


}
