/**
 * Routes for BindOutcome
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: arbitration
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { bindArbitrationOutcome } from "../handlers/bind-outcome.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function bindOutcomeRoutes(fastify: FastifyInstance) {
  // POST /v0/arbitration-cases/{caseId}/bind-outcome (unscoped; scope set for security middleware)
  fastify.post(
    "/v0/arbitration-cases/:caseId/bind-outcome",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { caseId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getArbitrationDependenciesForRequest();
        await bindArbitrationOutcome(request, reply, deps);
      });
    }
  );


}
