/**
 * Routes index
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: arbitration
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export { arbitrationCaseRoutes } from "./arbitration-case.routes.js";
export { bindOutcomeRoutes } from "./bind-outcome.routes.js";
export { decideRoutes } from "./decide.routes.js";
