/**
 * OpenRewardEpoch handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: rewards
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { openRewardEpoch } from "@veridrop/api-server/domains/rewards/handlers";
import type { RewardsDDDDependencies } from "@veridrop/api-server/domains/rewards";
import { createRewardEpoch as createRewardEpochEntity } from "@veridrop/factories/rewards";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@veridrop/tests/shared";
import { REWARDS_USE_CASES } from "../__factories__/use-cases.js";

describe("OpenRewardEpoch", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: RewardsDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<RewardsDDDDependencies>(
      REWARDS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 201 with created entity", async () => {
    const input = {} as any;
    const entity = createRewardEpochEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeOpenRewardEpoch, "execute").mockResolvedValue(useCaseResult);

    await openRewardEpoch(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeOpenRewardEpoch.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(201);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
