/**
 * EmissionPauseRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: governance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * EmissionPauseRepository Port
 *
 * DDD: Application port for emissionpauserepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { GetEmissionPauseStateInput, GetEmissionPauseStateOutput, SetEmissionPauseStateInput, SetEmissionPauseStateOutput } from "../dto/emission-pause.dto";
export interface EmissionPauseRepository {
  getEmissionPauseState(input: GetEmissionPauseStateInput): Promise<GetEmissionPauseStateOutput>;
  setEmissionPauseState(input: SetEmissionPauseStateInput): Promise<SetEmissionPauseStateOutput>;
}

export type { GetEmissionPauseStateInput, GetEmissionPauseStateOutput, SetEmissionPauseStateInput, SetEmissionPauseStateOutput } from "../dto/emission-pause.dto";
