/**
 * ExecuteRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: governance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteRepository Port
 *
 * DDD: Application port for executerepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { ExecuteParameterVersionInput, ExecuteParameterVersionOutput } from "../dto/execute.dto";
export interface ExecuteRepository {
  executeParameterVersion(input: ExecuteParameterVersionInput): Promise<ExecuteParameterVersionOutput>;
}

export type { ExecuteParameterVersionInput, ExecuteParameterVersionOutput } from "../dto/execute.dto";
