/**
 * ParameterVersionRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: governance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ParameterVersionRepository Port
 *
 * DDD: Application port for parameterversionrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { GetParameterVersionInput, GetParameterVersionOutput, ListParameterVersionsInput, ListParameterVersionsOutput, ProposeParameterVersionInput, ProposeParameterVersionOutput } from "../dto/parameter-version.dto";
export interface ParameterVersionRepository {
  listParameterVersions(input: ListParameterVersionsInput): Promise<ListParameterVersionsOutput>;
  proposeParameterVersion(input: ProposeParameterVersionInput): Promise<ProposeParameterVersionOutput>;
  getParameterVersion(input: GetParameterVersionInput): Promise<GetParameterVersionOutput>;
}

export type { GetParameterVersionInput, GetParameterVersionOutput, ListParameterVersionsInput, ListParameterVersionsOutput, ProposeParameterVersionInput, ProposeParameterVersionOutput } from "../dto/parameter-version.dto";
