/**
 * ExecuteGetEmissionPauseState - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: governance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteGetEmissionPauseState Use Case
 *
 * DDD: Application use case for get EmissionPause.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { GetEmissionPauseStateInput, GetEmissionPauseStateOutput } from "../dto/emission-pause.dto";
import type { ExecutionContextService, IdGeneratorService } from "@veridrop/services/_shared/index.js";
import type { EmissionPauseRepository } from "../ports";
import { NotFoundError } from "../errors";

export class ExecuteGetEmissionPauseState {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly emissionPause: EmissionPauseRepository
  ) {}

  async execute(input: GetEmissionPauseStateInput): Promise<GetEmissionPauseStateOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.govId();

    // All field names extracted from OpenAPI spec: none
    // Load entity via repository (no ID field - uses input directly, pass correlation ID for response meta)
    const entity = await this.emissionPause.getEmissionPauseState({ ...input, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found`);
    }

    return entity as GetEmissionPauseStateOutput;
  }
}
