/**
 * Repository interface for ArbitrationCase
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: arbitration
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CreateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  ArbitrationCaseEntity
} from "../models/arbitration-case.entity.js";
import type {
  ListArbitrationCasesParams,
  ArbitrationCase
} from "../types/index.js";
/**
 * ArbitrationCaseRepository Interface
 */
export interface ArbitrationCaseRepository extends CreateReadRepository<ArbitrationCaseEntity, ArbitrationCase, string, ListArbitrationCasesParams> {

}
