/**
 * ProvenanceRecord Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: provenance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { ProvenanceRecordEntity } from "@veridrop/core/provenance/models/index.js";
import { provenanceSchemas } from "@veridrop/core/provenance";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "prv";

export function createProvenanceRecord(overrides: Partial<ProvenanceRecordEntity> = {}) {
  const raw = {
    id: overrides.id ?? `${DOMAIN_PREFIX}_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    attributionDigest: overrides.attributionDigest ?? faker.lorem.word(),
    provenanceId: overrides.provenanceId ?? `prv_${ulid().toLowerCase()}`,
    serviceId: overrides.serviceId ?? faker.string.uuid(),
    status: overrides.status ?? "recorded",
    ...overrides,
  };

  return provenanceSchemas.ProvenanceRecord.parse(raw);
}

export function provenanceRecordBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createProvenanceRecord(overrides));
}
