/**
 * ExecuteGetDropPosition - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: curation
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteGetDropPosition Use Case
 *
 * DDD: Application use case for get DropPosition.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { GetDropPositionInput, GetDropPositionOutput } from "../dto/drop-position.dto";
import type { ExecutionContextService, IdGeneratorService } from "@veridrop/services/_shared/index.js";
import type { DropPositionRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteGetDropPosition {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly dropPosition: DropPositionRepository
  ) {}

  async execute(input: GetDropPositionInput): Promise<GetDropPositionOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.curId();

    // All field names extracted from OpenAPI spec: none
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).positionId) {
      throw new ValidationError("positionId is required");
    }
    const positionId = (input as any).positionId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.dropPosition.getDropPosition({ positionId: positionId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${positionId}`);
    }

    return entity as GetDropPositionOutput;
  }
}
