/**
 * ExecuteListDropPositions - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: curation
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListDropPositions Use Case
 *
 * DDD: Application use case for list DropPosition.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListDropPositionsInput, ListDropPositionsOutput } from "../dto/drop-position.dto";
import type { ExecutionContextService, IdGeneratorService } from "@veridrop/services/_shared/index.js";
import type { DropPositionRepository } from "../ports";

export class ExecuteListDropPositions {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly dropPosition: DropPositionRepository
  ) {}

  async execute(input: ListDropPositionsInput): Promise<ListDropPositionsOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.curId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.dropPosition.listDropPositions({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListDropPositionsOutput;
  }
}
