/**
 * RevokeAccess DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: agreements
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * RevokeAccess DTOs
 *
 * DDD: Application DTOs for RevokeAccess use cases.
 */

import type { RevokeAgreementAccessParams, RevokeAgreementAccessRequestInput } from "@veridrop/core/agreements/types";

export type RevokeAgreementAccessInput = RevokeAgreementAccessParams & RevokeAgreementAccessRequestInput;

export type RevokeAgreementAccessOutput = {};
