/**
 * SetEmissionPauseState handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: governance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { setEmissionPauseState } from "@veridrop/api-server/domains/governance/handlers";
import type { GovernanceDDDDependencies } from "@veridrop/api-server/domains/governance";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@veridrop/tests/shared";
import { GOVERNANCE_USE_CASES } from "../__factories__/use-cases.js";

describe("SetEmissionPauseState", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: GovernanceDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<GovernanceDDDDependencies>(
      GOVERNANCE_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with updated entity", async () => {
    const entity = { id: 'mock-id', orgId } as any;
    const input = {} as any;
    const updatedEntity = { ...entity, ...input };
    const useCaseResult = { data: updatedEntity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.params = { id: entity.id };
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeSetEmissionPauseState, "execute").mockResolvedValue(useCaseResult);

    await setEmissionPauseState(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeSetEmissionPauseState.execute).toHaveBeenCalledWith(expect.objectContaining({ id: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
