/**
 * GetServiceAgreement handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: agreements
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { getServiceAgreement } from "@veridrop/api-server/domains/agreements/handlers";
import type { AgreementsDDDDependencies } from "@veridrop/api-server/domains/agreements";
import { createServiceAgreement as createServiceAgreementEntity } from "@veridrop/factories/agreements";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@veridrop/tests/shared";
import { AGREEMENTS_USE_CASES } from "../__factories__/use-cases.js";

describe("GetServiceAgreement", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: AgreementsDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<AgreementsDDDDependencies>(
      AGREEMENTS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with entity when found", async () => {
    const entity = createServiceAgreementEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    vi.spyOn(mockDeps.executeGetServiceAgreement, "execute").mockResolvedValue(useCaseResult);
    mockRequest.params = { agreementId: entity.id };

    await getServiceAgreement(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeGetServiceAgreement.execute).toHaveBeenCalledWith(expect.objectContaining({ agreementId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

  it("should return error when entity not found", async () => {
    const nonExistentId = "non-existent-id";
    mockRequest.params = { agreementId: nonExistentId };
    
    vi.spyOn(mockDeps.executeGetServiceAgreement, "execute").mockRejectedValue(
      new Error("Entity not found")
    );

    await expect(
      getServiceAgreement(mockRequest, mockReply, mockDeps)
    ).rejects.toThrow();
  });

});
