/**
 * ListServiceAgreements handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: agreements
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { listServiceAgreements } from "@veridrop/api-server/domains/agreements/handlers";
import type { AgreementsDDDDependencies } from "@veridrop/api-server/domains/agreements";
import { createServiceAgreement as createServiceAgreementEntity } from "@veridrop/factories/agreements";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@veridrop/tests/shared";
import { AGREEMENTS_USE_CASES } from "../__factories__/use-cases.js";

describe("ListServiceAgreements", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: AgreementsDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<AgreementsDDDDependencies>(
      AGREEMENTS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with list of entities", async () => {
    const entities = [
      createServiceAgreementEntity({ orgId }),
      createServiceAgreementEntity({ orgId }),
    ];
    const useCaseResult = {
      data: { items: entities, nextCursor: undefined, prevCursor: undefined },
      meta: { correlationId: "test", timestamp: new Date().toISOString(), pagination: {} }
    };
    
    vi.spyOn(mockDeps.executeListServiceAgreements, "execute").mockResolvedValue(useCaseResult);

    await listServiceAgreements(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeListServiceAgreements.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
