/**
 * AcceptDeliveryRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: agreements
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * AcceptDeliveryRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements AcceptDeliveryRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  AcceptDeliveryRepository,
} from "@veridrop/services/agreements";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { AcceptDeliveryRepositoryDdb } from "./accept-delivery-repository.ddb.js";

/**
 * AcceptDeliveryRepositoryAdapter
 *
 * Implements AcceptDeliveryRepository port for infrastructure layer.
 */
export class AcceptDeliveryRepositoryAdapter implements AcceptDeliveryRepository {
  private readonly ddb: AcceptDeliveryRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new AcceptDeliveryRepositoryDdb(this.dynamoClient);
  }

  async acceptAgreementDelivery(input: Parameters<AcceptDeliveryRepository['acceptAgreementDelivery']>[0]): Promise<Awaited<ReturnType<AcceptDeliveryRepository['acceptAgreementDelivery']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.acceptAgreementDelivery(input);
  }
}
