/**
 * RevokeAccessRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: agreements
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * RevokeAccessRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements RevokeAccessRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  RevokeAccessRepository,
} from "@veridrop/services/agreements";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { RevokeAccessRepositoryDdb } from "./revoke-access-repository.ddb.js";

/**
 * RevokeAccessRepositoryAdapter
 *
 * Implements RevokeAccessRepository port for infrastructure layer.
 */
export class RevokeAccessRepositoryAdapter implements RevokeAccessRepository {
  private readonly ddb: RevokeAccessRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new RevokeAccessRepositoryDdb(this.dynamoClient);
  }

  async revokeAgreementAccess(input: Parameters<RevokeAccessRepository['revokeAgreementAccess']>[0]): Promise<Awaited<ReturnType<RevokeAccessRepository['revokeAgreementAccess']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.revokeAgreementAccess(input);
  }
}
