/**
 * ServiceAgreementRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: agreements
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ServiceAgreementRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements ServiceAgreementRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  ServiceAgreementRepository,
} from "@veridrop/services/agreements";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { ServiceAgreementRepositoryDdb } from "./service-agreement-repository.ddb.js";

/**
 * ServiceAgreementRepositoryAdapter
 *
 * Implements ServiceAgreementRepository port for infrastructure layer.
 */
export class ServiceAgreementRepositoryAdapter implements ServiceAgreementRepository {
  private readonly ddb: ServiceAgreementRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new ServiceAgreementRepositoryDdb(this.dynamoClient);
  }

  async listServiceAgreements(input: Parameters<ServiceAgreementRepository['listServiceAgreements']>[0]): Promise<Awaited<ReturnType<ServiceAgreementRepository['listServiceAgreements']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listServiceAgreements(input);
  }

  async createServiceAgreement(input: Parameters<ServiceAgreementRepository['createServiceAgreement']>[0]): Promise<Awaited<ReturnType<ServiceAgreementRepository['createServiceAgreement']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.createServiceAgreement(input);
  }

  async getServiceAgreement(input: Parameters<ServiceAgreementRepository['getServiceAgreement']>[0]): Promise<Awaited<ReturnType<ServiceAgreementRepository['getServiceAgreement']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getServiceAgreement(input);
  }
}
