/**
 * Use Case List
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: rewards
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Rewards Domain Use Cases
 * 
 * List of all use case names for the rewards domain.
 * Used by createMockDependencies() to pre-create mocks.
 */

export const REWARDS_USE_CASES = [
  "executeAllocateRewardEpoch",
  "executeClawbackRewardEpoch",
  "executeCloseRewardEpoch",
  "executeExportRewardEpochAudit",
  "executeGetRewardEpoch",
  "executeListRewardEpochs",
  "executeOpenRewardEpoch",
  "executePauseRewardEpoch"
] as const;
