/**
 * AcceptRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: proofs
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * AcceptRepository Port
 *
 * DDD: Application port for acceptrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { AcceptDeliveryProofInput, AcceptDeliveryProofOutput } from "../dto/accept.dto";
export interface AcceptRepository {
  acceptDeliveryProof(input: AcceptDeliveryProofInput): Promise<AcceptDeliveryProofOutput>;
}

export type { AcceptDeliveryProofInput, AcceptDeliveryProofOutput } from "../dto/accept.dto";
