/**
 * DeliveryProofRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: proofs
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * DeliveryProofRepository Port
 *
 * DDD: Application port for deliveryproofrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { GetDeliveryProofInput, GetDeliveryProofOutput, ListDeliveryProofsInput, ListDeliveryProofsOutput, SubmitDeliveryProofInput, SubmitDeliveryProofOutput } from "../dto/delivery-proof.dto";
export interface DeliveryProofRepository {
  listDeliveryProofs(input: ListDeliveryProofsInput): Promise<ListDeliveryProofsOutput>;
  submitDeliveryProof(input: SubmitDeliveryProofInput): Promise<SubmitDeliveryProofOutput>;
  getDeliveryProof(input: GetDeliveryProofInput): Promise<GetDeliveryProofOutput>;
}

export type { GetDeliveryProofInput, GetDeliveryProofOutput, ListDeliveryProofsInput, ListDeliveryProofsOutput, SubmitDeliveryProofInput, SubmitDeliveryProofOutput } from "../dto/delivery-proof.dto";
