/**
 * SlashRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: proofs
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * SlashRepository Port
 *
 * DDD: Application port for slashrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { SlashDeliveryProofInput, SlashDeliveryProofOutput } from "../dto/slash.dto";
export interface SlashRepository {
  slashDeliveryProof(input: SlashDeliveryProofInput): Promise<SlashDeliveryProofOutput>;
}

export type { SlashDeliveryProofInput, SlashDeliveryProofOutput } from "../dto/slash.dto";
