/**
 * DropPositionRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: curation
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * DropPositionRepository Port
 *
 * DDD: Application port for droppositionrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { GetDropPositionInput, GetDropPositionOutput, ListDropPositionsInput, ListDropPositionsOutput, OpenDropPositionInput, OpenDropPositionOutput } from "../dto/drop-position.dto";
export interface DropPositionRepository {
  listDropPositions(input: ListDropPositionsInput): Promise<ListDropPositionsOutput>;
  openDropPosition(input: OpenDropPositionInput): Promise<OpenDropPositionOutput>;
  getDropPosition(input: GetDropPositionInput): Promise<GetDropPositionOutput>;
}

export type { GetDropPositionInput, GetDropPositionOutput, ListDropPositionsInput, ListDropPositionsOutput, OpenDropPositionInput, OpenDropPositionOutput } from "../dto/drop-position.dto";
