/**
 * ChallengeEscapeRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: provenance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ChallengeEscapeRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements ChallengeEscapeRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  ChallengeEscapeRepository,
} from "@veridrop/services/provenance";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { ChallengeEscapeRepositoryDdb } from "./challenge-escape-repository.ddb.js";

/**
 * ChallengeEscapeRepositoryAdapter
 *
 * Implements ChallengeEscapeRepository port for infrastructure layer.
 */
export class ChallengeEscapeRepositoryAdapter implements ChallengeEscapeRepository {
  private readonly ddb: ChallengeEscapeRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new ChallengeEscapeRepositoryDdb(this.dynamoClient);
  }

  async challengeDataEscape(input: Parameters<ChallengeEscapeRepository['challengeDataEscape']>[0]): Promise<Awaited<ReturnType<ChallengeEscapeRepository['challengeDataEscape']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.challengeDataEscape(input);
  }
}
