/**
 * Arbitration DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: arbitration
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Arbitration Domain Module - Composition root
 *
 * DDD: Composition root for arbitration domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  ArbitrationCaseRepositoryAdapter,
  BindOutcomeRepositoryAdapter,
  DecideRepositoryAdapter,
} from "@veridrop/adapters/arbitration";
import { getIdGeneratorService } from "@veridrop/adapters";
import type { AdapterDynamoDBClient } from "@veridrop/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteGetArbitrationCase,
  ExecuteListArbitrationCases,
  ExecuteOpenArbitrationCase,
} from "@veridrop/services/arbitration/usecases";
// Ports (interfaces)
import type {
  ArbitrationCaseRepository,
  BindOutcomeRepository,
  DecideRepository,
} from "@veridrop/services/arbitration/ports";

export interface ArbitrationDomainModule {
  repos: {
    bindOutcomes: BindOutcomeRepository;
    cases: ArbitrationCaseRepository;
    decides: DecideRepository;
  };
  useCases: {
    cases: {
      get: ExecuteGetArbitrationCase;
      list: ExecuteListArbitrationCases;
    };
  };
}

export function buildArbitrationDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): ArbitrationDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      bindOutcomes?: BindOutcomeRepository;
      cases?: ArbitrationCaseRepository;
      decides?: DecideRepository;
    } = {};

    obj.bindOutcomes = new BindOutcomeRepositoryAdapter(dynamoClient);
    obj.cases = new ArbitrationCaseRepositoryAdapter(dynamoClient);
    obj.decides = new DecideRepositoryAdapter(dynamoClient);
    return {
      bindOutcomes: obj.bindOutcomes!,
      cases: obj.cases!,
      decides: obj.decides!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    cases: {
      get: new ExecuteGetArbitrationCase(executionContext, idGenerator, repos.cases),
      list: new ExecuteListArbitrationCases(executionContext, idGenerator, repos.cases),
    },
  };
  return { repos, useCases: useCases as ArbitrationDomainModule["useCases"] };
}
