/**
 * ParameterVersion Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: governance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { ParameterVersionEntity } from "@veridrop/core/governance/models/index.js";
import { governanceSchemas } from "@veridrop/core/governance";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "gov";

export function createParameterVersion(overrides: Partial<ParameterVersionEntity> = {}) {
  const raw = {
    id: overrides.id ?? `${DOMAIN_PREFIX}_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    effectiveAfter: overrides.effectiveAfter ?? new Date().toISOString(),
    kind: overrides.kind ?? "bondingCurve",
    parameterVersionId: overrides.parameterVersionId ?? `prm_${ulid().toLowerCase()}`,
    proposedAt: overrides.proposedAt ?? new Date().toISOString(),
    status: overrides.status ?? "proposed",
    ...overrides,
  };

  return governanceSchemas.ParameterVersion.parse(raw);
}

export function parameterVersionBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createParameterVersion(overrides));
}
