/**
 * ListParameterVersion DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: governance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { ListParameterVersionsParams } from "@veridrop/core/governance";

export function createListParameterVersionRequest(overrides: Partial<ListParameterVersionsParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
