/**
 * Factories barrel export
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: rewards
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Factories Barrel Export
 *
 * Exports all entity and DTO factories for the rewards domain.
 * Use these factories in tests to create test data.
 */

export { createCreateCloseRequest } from "./close/dto/create-close.dto.factory.js";
export { createRewardEpoch } from "./reward-epoch/entity/reward-epoch.entity.factory.js";
