/**
 * GetDeliveryProof handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: proofs
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { getDeliveryProof } from "@veridrop/api-server/domains/proofs/handlers";
import type { ProofsDDDDependencies } from "@veridrop/api-server/domains/proofs";
import { createDeliveryProof as createDeliveryProofEntity } from "@veridrop/factories/proofs";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@veridrop/tests/shared";
import { PROOFS_USE_CASES } from "../__factories__/use-cases.js";

describe("GetDeliveryProof", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: ProofsDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<ProofsDDDDependencies>(
      PROOFS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with entity when found", async () => {
    const entity = createDeliveryProofEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    vi.spyOn(mockDeps.executeGetDeliveryProof, "execute").mockResolvedValue(useCaseResult);
    mockRequest.params = { proofId: entity.id };

    await getDeliveryProof(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeGetDeliveryProof.execute).toHaveBeenCalledWith(expect.objectContaining({ proofId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

  it("should return error when entity not found", async () => {
    const nonExistentId = "non-existent-id";
    mockRequest.params = { proofId: nonExistentId };
    
    vi.spyOn(mockDeps.executeGetDeliveryProof, "execute").mockRejectedValue(
      new Error("Entity not found")
    );

    await expect(
      getDeliveryProof(mockRequest, mockReply, mockDeps)
    ).rejects.toThrow();
  });

});
