/**
 * ListDeliveryProofs handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: proofs
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { listDeliveryProofs } from "@veridrop/api-server/domains/proofs/handlers";
import type { ProofsDDDDependencies } from "@veridrop/api-server/domains/proofs";
import { createDeliveryProof as createDeliveryProofEntity } from "@veridrop/factories/proofs";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@veridrop/tests/shared";
import { PROOFS_USE_CASES } from "../__factories__/use-cases.js";

describe("ListDeliveryProofs", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: ProofsDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<ProofsDDDDependencies>(
      PROOFS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with list of entities", async () => {
    const entities = [
      createDeliveryProofEntity({ orgId }),
      createDeliveryProofEntity({ orgId }),
    ];
    const useCaseResult = {
      data: { items: entities, nextCursor: undefined, prevCursor: undefined },
      meta: { correlationId: "test", timestamp: new Date().toISOString(), pagination: {} }
    };
    
    vi.spyOn(mockDeps.executeListDeliveryProofs, "execute").mockResolvedValue(useCaseResult);

    await listDeliveryProofs(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeListDeliveryProofs.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
