/**
 * Repository interface for ProvenanceRecord
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: provenance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CreateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  ProvenanceRecordEntity
} from "../models/provenance-record.entity.js";
import type {
  ListProvenanceRecordsParams,
  ProvenanceRecord
} from "../types/index.js";
/**
 * ProvenanceRecordRepository Interface
 */
export interface ProvenanceRecordRepository extends CreateReadRepository<ProvenanceRecordEntity, ProvenanceRecord, string, ListProvenanceRecordsParams> {

}
