/**
 * Handlers for Accept
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: proofs
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { ProofsDomainModule } from "../dependencies/proofs-ddd.dependencies.js";
import type { AcceptDeliveryProofInput } from "@veridrop/services/proofs";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for POST /v0/delivery-proofs/{proofId}/accept
 * Operation: acceptDeliveryProof
 */
export async function acceptDeliveryProof(
  request: FastifyRequest<{ Params: { proofId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: ProofsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: AcceptDeliveryProofInput = {
    proofId: request.params.proofId,
  };
  const result = await deps.useCases.accepts.get.execute(input);
  return reply.code(200).send(result);
}


