/**
 * Handlers for DeliveryProof
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: proofs
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { ProofsDomainModule } from "../dependencies/proofs-ddd.dependencies.js";
import type { GetDeliveryProofInput, ListDeliveryProofsInput, SubmitDeliveryProofInput } from "@veridrop/services/proofs";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v0/delivery-proofs
 * Operation: listDeliveryProofs
 */
export async function listDeliveryProofs(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[], verdict?: string | string[], serviceId?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: ProofsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListDeliveryProofsInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.deliveryProofs.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v0/delivery-proofs
 * Operation: submitDeliveryProof
 */
export async function submitDeliveryProof(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: ProofsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: SubmitDeliveryProofInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.deliveryProofs.create.execute(input);
  return reply.code(201).send(result);
}


/**
 * Handler for GET /v0/delivery-proofs/{proofId}
 * Operation: getDeliveryProof
 */
export async function getDeliveryProof(
  request: FastifyRequest<{ Params: { proofId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: ProofsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetDeliveryProofInput = {
    proofId: request.params.proofId,
  };
  const result = await deps.useCases.deliveryProofs.get.execute(input);
  return reply.code(200).send(result);
}


