/**
 * Handlers for Service
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: services
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { ServicesDomainModule } from "../dependencies/services-ddd.dependencies.js";
import type { GetServiceInput, ListServicesInput, RegisterServiceInput } from "@veridrop/services/services";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v0/services
 * Operation: listServices
 */
export async function listServices(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[], status?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: ServicesDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListServicesInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.services.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v0/services
 * Operation: registerService
 */
export async function registerService(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: ServicesDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: RegisterServiceInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.services.create.execute(input);
  return reply.code(201).send(result);
}


/**
 * Handler for GET /v0/services/{serviceId}
 * Operation: getService
 */
export async function getService(
  request: FastifyRequest<{ Params: { serviceId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: ServicesDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetServiceInput = {
    serviceId: request.params.serviceId,
  };
  const result = await deps.useCases.services.get.execute(input);
  return reply.code(200).send(result);
}


