/**
 * Main Services Package Index
 *
 * Generated by Services Main Index Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: governance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Services Package - Main Barrel Export
 *
 * Central export point for all application services (use cases, ports, DTOs, policies, errors)
 * Organized by domain for easy importing
 *
 * Usage:
 *   // Namespace imports (recommended)
 *   import { activity, ai, conversation } from "@veridrop/services";
 *   const { usecases, dto, ports } = activity;
 *
 *   // Direct imports from domain
 *   import { ExecuteCreateEventUseCase } from "@veridrop/services/activity";
 *   
 *   // Shared services
 *   import { executionContextService } from "@veridrop/services";
 */

// ============================================================================
// SHARED SERVICES EXPORTS
// ============================================================================
export { executionContextService } from "./_shared/index.js";

// ============================================================================
// DOMAIN EXPORTS (using namespace to avoid duplicate type conflicts)
// ============================================================================
// Export domains as namespaces to prevent TS2308 errors from duplicate exports
// of shared types across domains

import * as _agreements from "./agreements/index.js";
import * as _arbitration from "./arbitration/index.js";
import * as _curation from "./curation/index.js";
import * as _governance from "./governance/index.js";
import * as _identity from "./identity/index.js";
import * as _participants from "./participants/index.js";
import * as _proofs from "./proofs/index.js";
import * as _provenance from "./provenance/index.js";
import * as _rewards from "./rewards/index.js";
import * as _services from "./services/index.js";

// Export as namespaces
export const agreements = _agreements;
export const arbitration = _arbitration;
export const curation = _curation;
export const governance = _governance;
export const identity = _identity;
export const participants = _participants;
export const proofs = _proofs;
export const provenance = _provenance;
export const rewards = _rewards;
export const services = _services;
