/**
 * Factories barrel export
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: curation
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Factories Barrel Export
 *
 * Exports all entity and DTO factories for the curation domain.
 * Use these factories in tests to create test data.
 */

export { createDropPosition } from "./drop-position/entity/drop-position.entity.factory.js";
export { createStakeEvent } from "./stake-event/entity/stake-event.entity.factory.js";
