/**
 * Unstake DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: curation
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Unstake DTOs
 *
 * DDD: Application DTOs for Unstake use cases.
 */

import type { UnstakeDropPositionParams, UnstakeDropPositionRequestInput } from "@veridrop/core/curation/types";

export type UnstakeDropPositionInput = UnstakeDropPositionParams & UnstakeDropPositionRequestInput;

export type UnstakeDropPositionOutput = {};
