/**
 * Routes for DropPosition
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: curation
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { getDropPosition, listDropPositions, openDropPosition } from "../handlers/drop-position.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function dropPositionRoutes(fastify: FastifyInstance) {
  // GET /v0/drop-positions (unscoped; scope set for security middleware)
  fastify.get(
    "/v0/drop-positions",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getCurationDependenciesForRequest();
        await listDropPositions(request, reply, deps);
      });
    }
  );


  // POST /v0/drop-positions (unscoped; scope set for security middleware)
  fastify.post(
    "/v0/drop-positions",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getCurationDependenciesForRequest();
        await openDropPosition(request, reply, deps);
      });
    }
  );


  // GET /v0/drop-positions/{positionId} (unscoped; scope set for security middleware)
  fastify.get(
    "/v0/drop-positions/:positionId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { positionId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getCurationDependenciesForRequest();
        await getDropPosition(request, reply, deps);
      });
    }
  );


}
