/**
 * Routes for StakeEvent
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: curation
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { listStakeEvents } from "../handlers/stake-event.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function stakeEventRoutes(fastify: FastifyInstance) {
  // GET /v0/drop-positions/{positionId}/stake-events (unscoped; scope set for security middleware)
  fastify.get(
    "/v0/drop-positions/:positionId/stake-events",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { positionId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getCurationDependenciesForRequest();
        await listStakeEvents(request, reply, deps);
      });
    }
  );


}
