/**
 * Handlers for EmissionPause
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: governance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { GovernanceDomainModule } from "../dependencies/governance-ddd.dependencies.js";
import type { GetEmissionPauseStateInput, SetEmissionPauseStateInput } from "@veridrop/services/governance";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v0/governance/emission-pause
 * Operation: getEmissionPauseState
 */
export async function getEmissionPauseState(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: GovernanceDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetEmissionPauseStateInput = {};
  const result = await deps.useCases.emissionPauses.get.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v0/governance/emission-pause
 * Operation: setEmissionPauseState
 */
export async function setEmissionPauseState(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: GovernanceDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: SetEmissionPauseStateInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.emissionPauses.update.execute(input);
  return reply.code(200).send(result);
}


