/**
 * Handlers for ParameterVersion
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: governance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { GovernanceDomainModule } from "../dependencies/governance-ddd.dependencies.js";
import type { GetParameterVersionInput, ListParameterVersionsInput, ProposeParameterVersionInput } from "@veridrop/services/governance";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v0/parameter-versions
 * Operation: listParameterVersions
 */
export async function listParameterVersions(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[], status?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: GovernanceDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListParameterVersionsInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.parameterVersions.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v0/parameter-versions
 * Operation: proposeParameterVersion
 */
export async function proposeParameterVersion(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: GovernanceDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ProposeParameterVersionInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.parameterVersions.get.execute(input);
  return reply.code(201).send(result);
}


/**
 * Handler for GET /v0/parameter-versions/{parameterVersionId}
 * Operation: getParameterVersion
 */
export async function getParameterVersion(
  request: FastifyRequest<{ Params: { parameterVersionId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: GovernanceDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetParameterVersionInput = {
    parameterVersionId: request.params.parameterVersionId,
  };
  const result = await deps.useCases.parameterVersions.get.execute(input);
  return reply.code(200).send(result);
}


