/**
 * ListRewardEpoch DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: rewards
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { ListRewardEpochsParams } from "@veridrop/core/rewards";

export function createListRewardEpochRequest(overrides: Partial<ListRewardEpochsParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
