/**
 * Service Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: services
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/services.openapi.types.js";
import { schemas } from "../schemas/services.schemas.js";

/**
 * Entity: ServiceEntity
 * Description: Represents the Service domain model.
 * Source: schemas.Service
 * Type: Domain Entity (API)
 */
export const ServiceEntitySchema = schemas.Service;
export type ServiceEntity = components["schemas"]["Service"];
