/**
 * Routes for Execute
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: governance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { executeParameterVersion } from "../handlers/execute.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function executeRoutes(fastify: FastifyInstance) {
  // POST /v0/parameter-versions/{parameterVersionId}/execute (unscoped; scope set for security middleware)
  fastify.post(
    "/v0/parameter-versions/:parameterVersionId/execute",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { parameterVersionId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getGovernanceDependenciesForRequest();
        await executeParameterVersion(request, reply, deps);
      });
    }
  );


}
