/**
 * Routes for ParameterVersion
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: governance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { getParameterVersion, listParameterVersions, proposeParameterVersion } from "../handlers/parameter-version.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function parameterVersionRoutes(fastify: FastifyInstance) {
  // GET /v0/parameter-versions (unscoped; scope set for security middleware)
  fastify.get(
    "/v0/parameter-versions",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getGovernanceDependenciesForRequest();
        await listParameterVersions(request, reply, deps);
      });
    }
  );


  // POST /v0/parameter-versions (unscoped; scope set for security middleware)
  fastify.post(
    "/v0/parameter-versions",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getGovernanceDependenciesForRequest();
        await proposeParameterVersion(request, reply, deps);
      });
    }
  );


  // GET /v0/parameter-versions/{parameterVersionId} (unscoped; scope set for security middleware)
  fastify.get(
    "/v0/parameter-versions/:parameterVersionId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { parameterVersionId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getGovernanceDependenciesForRequest();
        await getParameterVersion(request, reply, deps);
      });
    }
  );


}
