/**
 * GetServiceAgreement DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: agreements
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { GetServiceAgreementParams } from "@veridrop/core/agreements";

export function createGetServiceAgreementRequest(overrides: Partial<GetServiceAgreementParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
