/**
 * Use Case List
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: agreements
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Agreements Domain Use Cases
 * 
 * List of all use case names for the agreements domain.
 * Used by createMockDependencies() to pre-create mocks.
 */

export const AGREEMENTS_USE_CASES = [
  "executeAcceptAgreementDelivery",
  "executeCreateServiceAgreement",
  "executeGetServiceAgreement",
  "executeListServiceAgreements",
  "executeRevokeAgreementAccess"
] as const;
