/**
 * Governance Zod Schemas - Runtime validation schemas
 *
 * Generated by Zod Schemas Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: governance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import { makeApi, Zodios, type ZodiosOptions } from '@zodios/core';
import { z } from 'zod';

const proposeParameterVersion_Body = z
  .object({
    kind: z.enum(['bondingCurve', 'rewardSchedule', 'emissionPausePolicy']),
    summary: z.string().max(500).optional(),
    delayHours: z.number().int().gte(1).lte(720),
    payloadDigest: z.string().min(1),
  })
  .passthrough();
const setEmissionPauseState_Body = z
  .object({
    paused: z.boolean(),
    proofTypes: z
      .array(z.enum(['availability', 'zkCompute', 'replication']))
      .optional(),
    reason: z.string().max(500).optional(),
  })
  .passthrough();

export const schemas: any = {
  proposeParameterVersion_Body,
  setEmissionPauseState_Body,
};

const endpoints = makeApi([
  {
    method: 'get',
    path: '/v0/governance/emission-pause',
    alias: 'getEmissionPauseState',
    requestFormat: 'json',
    response: z
      .object({
        data: z
          .object({
            paused: z.boolean(),
            proofTypes: z
              .array(z.enum(['availability', 'zkCompute', 'replication']))
              .optional(),
            reason: z.string().optional(),
            updatedAt: z.string().datetime({ offset: true }),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
  },
  {
    method: 'post',
    path: '/v0/governance/emission-pause',
    alias: 'setEmissionPauseState',
    requestFormat: 'json',
    parameters: [
      {
        name: 'body',
        type: 'Body',
        schema: setEmissionPauseState_Body,
      },
      {
        name: 'Idempotency-Key',
        type: 'Header',
        schema: z.string().min(1).max(128),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            paused: z.boolean(),
            proofTypes: z
              .array(z.enum(['availability', 'zkCompute', 'replication']))
              .optional(),
            reason: z.string().optional(),
            updatedAt: z.string().datetime({ offset: true }),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
  },
  {
    method: 'get',
    path: '/v0/parameter-versions',
    alias: 'listParameterVersions',
    requestFormat: 'json',
    parameters: [
      {
        name: 'cursor',
        type: 'Query',
        schema: z.string().optional(),
      },
      {
        name: 'limit',
        type: 'Query',
        schema: z.number().int().gte(1).lte(100).optional().default(25),
      },
      {
        name: 'status',
        type: 'Query',
        schema: z
          .enum([
            'proposed',
            'pendingDelay',
            'active',
            'superseded',
            'cancelled',
          ])
          .optional(),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            items: z.array(
              z
                .object({
                  parameterVersionId: z
                    .string()
                    .regex(/^prm_[0-9A-HJKMNP-TV-Z]{26}$/),
                  kind: z.enum([
                    'bondingCurve',
                    'rewardSchedule',
                    'emissionPausePolicy',
                  ]),
                  status: z.enum([
                    'proposed',
                    'pendingDelay',
                    'active',
                    'superseded',
                    'cancelled',
                  ]),
                  summary: z.string().optional(),
                  payloadDigest: z.string().optional(),
                  proposedAt: z.string().datetime({ offset: true }),
                  effectiveAfter: z.string().datetime({ offset: true }),
                  executedAt: z.string().datetime({ offset: true }).optional(),
                  createdAt: z.string().datetime({ offset: true }),
                  updatedAt: z.string().datetime({ offset: true }),
                })
                .passthrough()
            ),
            nextCursor: z.string().optional(),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
  },
  {
    method: 'post',
    path: '/v0/parameter-versions',
    alias: 'proposeParameterVersion',
    requestFormat: 'json',
    parameters: [
      {
        name: 'body',
        type: 'Body',
        schema: proposeParameterVersion_Body,
      },
      {
        name: 'Idempotency-Key',
        type: 'Header',
        schema: z.string().min(1).max(128),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            parameterVersionId: z
              .string()
              .regex(/^prm_[0-9A-HJKMNP-TV-Z]{26}$/),
            kind: z.enum([
              'bondingCurve',
              'rewardSchedule',
              'emissionPausePolicy',
            ]),
            status: z.enum([
              'proposed',
              'pendingDelay',
              'active',
              'superseded',
              'cancelled',
            ]),
            summary: z.string().optional(),
            payloadDigest: z.string().optional(),
            proposedAt: z.string().datetime({ offset: true }),
            effectiveAfter: z.string().datetime({ offset: true }),
            executedAt: z.string().datetime({ offset: true }).optional(),
            createdAt: z.string().datetime({ offset: true }),
            updatedAt: z.string().datetime({ offset: true }),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
    errors: [
      {
        status: 400,
        description: `Malformed request`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
    ],
  },
  {
    method: 'get',
    path: '/v0/parameter-versions/:parameterVersionId',
    alias: 'getParameterVersion',
    requestFormat: 'json',
    parameters: [
      {
        name: 'parameterVersionId',
        type: 'Path',
        schema: z.string().regex(/^prm_[0-9A-HJKMNP-TV-Z]{26}$/),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            parameterVersionId: z
              .string()
              .regex(/^prm_[0-9A-HJKMNP-TV-Z]{26}$/),
            kind: z.enum([
              'bondingCurve',
              'rewardSchedule',
              'emissionPausePolicy',
            ]),
            status: z.enum([
              'proposed',
              'pendingDelay',
              'active',
              'superseded',
              'cancelled',
            ]),
            summary: z.string().optional(),
            payloadDigest: z.string().optional(),
            proposedAt: z.string().datetime({ offset: true }),
            effectiveAfter: z.string().datetime({ offset: true }),
            executedAt: z.string().datetime({ offset: true }).optional(),
            createdAt: z.string().datetime({ offset: true }),
            updatedAt: z.string().datetime({ offset: true }),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
    errors: [
      {
        status: 404,
        description: `Resource not found`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
    ],
  },
  {
    method: 'post',
    path: '/v0/parameter-versions/:parameterVersionId/execute',
    alias: 'executeParameterVersion',
    requestFormat: 'json',
    parameters: [
      {
        name: 'parameterVersionId',
        type: 'Path',
        schema: z.string().regex(/^prm_[0-9A-HJKMNP-TV-Z]{26}$/),
      },
      {
        name: 'Idempotency-Key',
        type: 'Header',
        schema: z.string().min(1).max(128),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            parameterVersionId: z
              .string()
              .regex(/^prm_[0-9A-HJKMNP-TV-Z]{26}$/),
            kind: z.enum([
              'bondingCurve',
              'rewardSchedule',
              'emissionPausePolicy',
            ]),
            status: z.enum([
              'proposed',
              'pendingDelay',
              'active',
              'superseded',
              'cancelled',
            ]),
            summary: z.string().optional(),
            payloadDigest: z.string().optional(),
            proposedAt: z.string().datetime({ offset: true }),
            effectiveAfter: z.string().datetime({ offset: true }),
            executedAt: z.string().datetime({ offset: true }).optional(),
            createdAt: z.string().datetime({ offset: true }),
            updatedAt: z.string().datetime({ offset: true }),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
    errors: [
      {
        status: 409,
        description: `Idempotency key reuse with different body, or state conflict`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
    ],
  },
]);

export const api: any = new Zodios('https://api.veridrop.local', endpoints);

export function createApiClient(baseUrl: string, options?: ZodiosOptions): any {
  return new Zodios(baseUrl, endpoints, options);
}
