/**
 * GetProvenanceRecord DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: provenance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { GetProvenanceRecordParams } from "@veridrop/core/provenance";

export function createGetProvenanceRecordRequest(overrides: Partial<GetProvenanceRecordParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
