/**
 * ArbitrationCase DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: arbitration
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ArbitrationCase DTOs
 *
 * DDD: Application DTOs for ArbitrationCase use cases.
 */

import type { GetArbitrationCaseParams, ListArbitrationCasesParams, OpenArbitrationCaseRequestInput } from "@veridrop/core/arbitration/types";

export type ListArbitrationCasesInput = ListArbitrationCasesParams;

export type OpenArbitrationCaseInput = OpenArbitrationCaseRequestInput;

export type GetArbitrationCaseInput = GetArbitrationCaseParams;

export type ListArbitrationCasesOutput = {};

export type OpenArbitrationCaseOutput = {};

export type GetArbitrationCaseOutput = {};
