/**
 * Provenance Zod Schemas - Runtime validation schemas
 *
 * Generated by Zod Schemas Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: provenance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import { makeApi, Zodios, type ZodiosOptions } from '@zodios/core';
import { z } from 'zod';

const recordProvenance_Body = z
  .object({
    serviceId: z.string(),
    attributionDigest: z.string().min(1),
    sourceParticipantId: z.string().optional(),
  })
  .passthrough();
const challengeDataEscape_Body = z
  .object({
    reason: z.string().min(1).max(2000),
    suspectedRepublicationRef: z.string().optional(),
  })
  .passthrough();

export const schemas: any = {
  recordProvenance_Body,
  challengeDataEscape_Body,
};

const endpoints = makeApi([
  {
    method: 'get',
    path: '/v0/provenance-records',
    alias: 'listProvenanceRecords',
    requestFormat: 'json',
    parameters: [
      {
        name: 'cursor',
        type: 'Query',
        schema: z.string().optional(),
      },
      {
        name: 'limit',
        type: 'Query',
        schema: z.number().int().gte(1).lte(100).optional().default(25),
      },
      {
        name: 'serviceId',
        type: 'Query',
        schema: z.string().optional(),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            items: z.array(
              z
                .object({
                  provenanceId: z
                    .string()
                    .regex(/^prv_[0-9A-HJKMNP-TV-Z]{26}$/),
                  serviceId: z.string(),
                  attributionDigest: z.string(),
                  sourceParticipantId: z.string().optional(),
                  status: z.enum([
                    'recorded',
                    'challenged',
                    'upheld',
                    'overturned',
                  ]),
                  challengeReason: z.string().optional(),
                  createdAt: z.string().datetime({ offset: true }),
                  updatedAt: z.string().datetime({ offset: true }),
                })
                .passthrough()
            ),
            nextCursor: z.string().optional(),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
  },
  {
    method: 'post',
    path: '/v0/provenance-records',
    alias: 'recordProvenance',
    requestFormat: 'json',
    parameters: [
      {
        name: 'body',
        type: 'Body',
        schema: recordProvenance_Body,
      },
      {
        name: 'Idempotency-Key',
        type: 'Header',
        schema: z.string().min(1).max(128),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            provenanceId: z.string().regex(/^prv_[0-9A-HJKMNP-TV-Z]{26}$/),
            serviceId: z.string(),
            attributionDigest: z.string(),
            sourceParticipantId: z.string().optional(),
            status: z.enum(['recorded', 'challenged', 'upheld', 'overturned']),
            challengeReason: z.string().optional(),
            createdAt: z.string().datetime({ offset: true }),
            updatedAt: z.string().datetime({ offset: true }),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
    errors: [
      {
        status: 400,
        description: `Malformed request`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
    ],
  },
  {
    method: 'get',
    path: '/v0/provenance-records/:provenanceId',
    alias: 'getProvenanceRecord',
    requestFormat: 'json',
    parameters: [
      {
        name: 'provenanceId',
        type: 'Path',
        schema: z.string().regex(/^prv_[0-9A-HJKMNP-TV-Z]{26}$/),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            provenanceId: z.string().regex(/^prv_[0-9A-HJKMNP-TV-Z]{26}$/),
            serviceId: z.string(),
            attributionDigest: z.string(),
            sourceParticipantId: z.string().optional(),
            status: z.enum(['recorded', 'challenged', 'upheld', 'overturned']),
            challengeReason: z.string().optional(),
            createdAt: z.string().datetime({ offset: true }),
            updatedAt: z.string().datetime({ offset: true }),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
    errors: [
      {
        status: 404,
        description: `Resource not found`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
    ],
  },
  {
    method: 'post',
    path: '/v0/provenance-records/:provenanceId/challenge-escape',
    alias: 'challengeDataEscape',
    requestFormat: 'json',
    parameters: [
      {
        name: 'body',
        type: 'Body',
        schema: challengeDataEscape_Body,
      },
      {
        name: 'provenanceId',
        type: 'Path',
        schema: z.string().regex(/^prv_[0-9A-HJKMNP-TV-Z]{26}$/),
      },
      {
        name: 'Idempotency-Key',
        type: 'Header',
        schema: z.string().min(1).max(128),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            provenanceId: z.string().regex(/^prv_[0-9A-HJKMNP-TV-Z]{26}$/),
            serviceId: z.string(),
            attributionDigest: z.string(),
            sourceParticipantId: z.string().optional(),
            status: z.enum(['recorded', 'challenged', 'upheld', 'overturned']),
            challengeReason: z.string().optional(),
            createdAt: z.string().datetime({ offset: true }),
            updatedAt: z.string().datetime({ offset: true }),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
  },
]);

export const api: any = new Zodios('https://api.veridrop.local', endpoints);

export function createApiClient(baseUrl: string, options?: ZodiosOptions): any {
  return new Zodios(baseUrl, endpoints, options);
}
