/**
 * Provenance DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: provenance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Provenance Domain Module - Composition root
 *
 * DDD: Composition root for provenance domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  ChallengeEscapeRepositoryAdapter,
  ProvenanceRecordRepositoryAdapter,
} from "@veridrop/adapters/provenance";
import { getIdGeneratorService } from "@veridrop/adapters";
import type { AdapterDynamoDBClient } from "@veridrop/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteGetProvenanceRecord,
  ExecuteListProvenanceRecords,
  ExecuteRecordProvenance,
} from "@veridrop/services/provenance/usecases";
// Ports (interfaces)
import type {
  ChallengeEscapeRepository,
  ProvenanceRecordRepository,
} from "@veridrop/services/provenance/ports";

export interface ProvenanceDomainModule {
  repos: {
    challengeEscapes: ChallengeEscapeRepository;
    records: ProvenanceRecordRepository;
  };
  useCases: {
    records: {
      get: ExecuteGetProvenanceRecord;
      list: ExecuteListProvenanceRecords;
    };
  };
}

export function buildProvenanceDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): ProvenanceDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      challengeEscapes?: ChallengeEscapeRepository;
      records?: ProvenanceRecordRepository;
    } = {};

    obj.challengeEscapes = new ChallengeEscapeRepositoryAdapter(dynamoClient);
    obj.records = new ProvenanceRecordRepositoryAdapter(dynamoClient);
    return {
      challengeEscapes: obj.challengeEscapes!,
      records: obj.records!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    records: {
      get: new ExecuteGetProvenanceRecord(executionContext, idGenerator, repos.records),
      list: new ExecuteListProvenanceRecords(executionContext, idGenerator, repos.records),
    },
  };
  return { repos, useCases: useCases as ProvenanceDomainModule["useCases"] };
}
