/**
 * Allocate DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: rewards
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Allocate DTOs
 *
 * DDD: Application DTOs for Allocate use cases.
 */

import type { AllocateRewardEpochParams, AllocateRewardEpochRequestInput } from "@veridrop/core/rewards/types";

export type AllocateRewardEpochInput = AllocateRewardEpochParams & AllocateRewardEpochRequestInput;

export type AllocateRewardEpochOutput = {};
