/**
 * RewardEpoch DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: rewards
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * RewardEpoch DTOs
 *
 * DDD: Application DTOs for RewardEpoch use cases.
 */

import type { GetRewardEpochParams, ListRewardEpochsParams, OpenRewardEpochRequestInput } from "@veridrop/core/rewards/types";

export type ListRewardEpochsInput = ListRewardEpochsParams;

export type OpenRewardEpochInput = OpenRewardEpochRequestInput;

export type GetRewardEpochInput = GetRewardEpochParams;

export type ListRewardEpochsOutput = {};

export type OpenRewardEpochOutput = {};

export type GetRewardEpochOutput = {};
