/**
 * Routes for ProofPolicy
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: services
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { setServiceProofPolicy } from "../handlers/proof-policy.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function proofPolicyRoutes(fastify: FastifyInstance) {
  // POST /v0/services/{serviceId}/proof-policy (unscoped; scope set for security middleware)
  fastify.post(
    "/v0/services/:serviceId/proof-policy",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { serviceId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getServicesDependenciesForRequest();
        await setServiceProofPolicy(request, reply, deps);
      });
    }
  );


}
