/**
 * ExecuteRegisterService - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: services
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteRegisterService Use Case
 *
 * DDD: Application use case for create Service.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { RegisterServiceInput, RegisterServiceOutput } from "../dto/service.dto";
import type { ExecutionContextService, IdGeneratorService } from "@veridrop/services/_shared/index.js";
import type { ServiceRepository } from "../ports";
import { PermissionDeniedError, ValidationError } from "../errors";
import { CanCreate } from "../policies/can-create.policy";
export class ExecuteRegisterService {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly service: ServiceRepository
  ) {}

  async execute(input: RegisterServiceInput): Promise<RegisterServiceOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.svcId();

    // All field names extracted from OpenAPI spec: pricingMode, proofTypeRequired, providerParticipantId, serviceType, title
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!input.serviceType) {
      throw new ValidationError("serviceType is required");
    }
    if (!input.providerParticipantId) {
      throw new ValidationError("providerParticipantId is required");
    }
    if (!input.proofTypeRequired) {
      throw new ValidationError("proofTypeRequired is required");
    }
    if (!input.pricingMode) {
      throw new ValidationError("pricingMode is required");
    }    // Check policy
    if (!CanCreate.allow({} as any, "")) {
      throw new PermissionDeniedError("Operation not allowed");
    }

    // Generate entity ID in services layer using IdGeneratorService (services domain)
    const entityId = this.idGenerator.svcId();

    // Create entity via repository (pass ID and correlation ID for response meta)
    const entity = await this.service.registerService({ ...input, id: entityId, createdByActorId: (input as any).createdByActorId ?? this.context.getUserId(), createdByActorType: (input as any).createdByActorType ?? "human", orgId: this.context.getOrgId(), correlationId } as any);

    return entity as RegisterServiceOutput;
  }
}
