/**
 * AllocateRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: rewards
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * AllocateRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements AllocateRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  AllocateRepository,
} from "@veridrop/services/rewards";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { AllocateRepositoryDdb } from "./allocate-repository.ddb.js";

/**
 * AllocateRepositoryAdapter
 *
 * Implements AllocateRepository port for infrastructure layer.
 */
export class AllocateRepositoryAdapter implements AllocateRepository {
  private readonly ddb: AllocateRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new AllocateRepositoryDdb(this.dynamoClient);
  }

  async allocateRewardEpoch(input: Parameters<AllocateRepository['allocateRewardEpoch']>[0]): Promise<Awaited<ReturnType<AllocateRepository['allocateRewardEpoch']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.allocateRewardEpoch(input);
  }
}
