/**
 * ExportAuditRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: rewards
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExportAuditRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements ExportAuditRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  ExportAuditRepository,
} from "@veridrop/services/rewards";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { AuditRepositoryDdb } from "./audit-repository.ddb.js";

/**
 * ExportAuditRepositoryAdapter
 *
 * Implements ExportAuditRepository port for infrastructure layer.
 */
export class ExportAuditRepositoryAdapter implements ExportAuditRepository {
  private readonly ddb: AuditRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new AuditRepositoryDdb(this.dynamoClient);
  }

  async exportRewardEpochAudit(input: Parameters<ExportAuditRepository['exportRewardEpochAudit']>[0]): Promise<Awaited<ReturnType<ExportAuditRepository['exportRewardEpochAudit']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.exportRewardEpochAudit(input);
  }
}
