/**
 * DynamoDB repository adapters barrel export
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: rewards
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export * from "./allocate-repository.ddb.js";
export * from "./audit-repository.ddb.js";
export * from "./clawback-repository.ddb.js";
export * from "./close-repository.ddb.js";
export * from "./pause-repository.ddb.js";
export * from "./reward-epoch-repository.ddb.js";
export * from "./allocate-repository.adapter.js";
export * from "./clawback-repository.adapter.js";
export * from "./close-repository.adapter.js";
export * from "./export-audit-repository.adapter.js";
export * from "./pause-repository.adapter.js";
export * from "./reward-epoch-repository.adapter.js";
