/**
 * ExecuteRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: governance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements ExecuteRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  ExecuteRepository,
} from "@veridrop/services/governance";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { ExecuteRepositoryDdb } from "./execute-repository.ddb.js";

/**
 * ExecuteRepositoryAdapter
 *
 * Implements ExecuteRepository port for infrastructure layer.
 */
export class ExecuteRepositoryAdapter implements ExecuteRepository {
  private readonly ddb: ExecuteRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new ExecuteRepositoryDdb(this.dynamoClient);
  }

  async executeParameterVersion(input: Parameters<ExecuteRepository['executeParameterVersion']>[0]): Promise<Awaited<ReturnType<ExecuteRepository['executeParameterVersion']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.executeParameterVersion(input);
  }
}
