/**
 * GetDeliveryProof DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: proofs
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { GetDeliveryProofParams } from "@veridrop/core/proofs";

export function createGetDeliveryProofRequest(overrides: Partial<GetDeliveryProofParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
