/**
 * AllocateRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: rewards
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * AllocateRepository Port
 *
 * DDD: Application port for allocaterepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { AllocateRewardEpochInput, AllocateRewardEpochOutput } from "../dto/allocate.dto";
export interface AllocateRepository {
  allocateRewardEpoch(input: AllocateRewardEpochInput): Promise<AllocateRewardEpochOutput>;
}

export type { AllocateRewardEpochInput, AllocateRewardEpochOutput } from "../dto/allocate.dto";
