/**
 * RewardEpochRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: rewards
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * RewardEpochRepository Port
 *
 * DDD: Application port for rewardepochrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { GetRewardEpochInput, GetRewardEpochOutput, ListRewardEpochsInput, ListRewardEpochsOutput, OpenRewardEpochInput, OpenRewardEpochOutput } from "../dto/reward-epoch.dto";
export interface RewardEpochRepository {
  listRewardEpochs(input: ListRewardEpochsInput): Promise<ListRewardEpochsOutput>;
  openRewardEpoch(input: OpenRewardEpochInput): Promise<OpenRewardEpochOutput>;
  getRewardEpoch(input: GetRewardEpochInput): Promise<GetRewardEpochOutput>;
}

export type { GetRewardEpochInput, GetRewardEpochOutput, ListRewardEpochsInput, ListRewardEpochsOutput, OpenRewardEpochInput, OpenRewardEpochOutput } from "../dto/reward-epoch.dto";
